app/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views
from app.views import index, about, contact_view, render, blog, login_view, single_post, logout_view, BlogSearchView, \
    Register, register_view

urlpatterns = [
    path('', index, name='index'),
    path('about/', about,name='about'),
    path('contact/',contact_view,name='contact'),
    path('single-post/<int:product_id>', single_post,name='single-post'),
    path('blog/', blog, name='blog'),
    path('login/', login_view, name='login'),
    path('logout/',logout_view,name='logout'),
    path('serch-blogs/',BlogSearchView.as_view(),name='search_blogs'),
    path('register/',register_view,name='register')
]
# adasd

logo/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views import static
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser, UserManager
from django.core.validators import integer_validator
from django.db import models
from django.db.models import CASCADE


class Category(models.Model):
    title = models.CharField(max_length=155)

    def __str__(self):
        return self.title


class Contact(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email


class Product(models.Model):
    img = models.ImageField(upload_to='product/')
    title = models.CharField(max_length=155)
    price = models.FloatField()
    text = models.TextField()
    category = models.ForeignKey('app.Category', on_delete=models.CASCADE)
    user = models.ForeignKey('app.User', on_delete=CASCADE)



class UserManager(BaseUserManager):

    def create_user(self,email, password=None,  **kwargs):
        if not email:
            raise ValueError('email not found')
        user = self.model(email=email,  **kwargs)
        user.set_password(password)
        user.save(self._db)
        return user

    def create_superuser(self,email, password, **kwargs):
        user = self.create_user(email, password, **kwargs)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=155, unique=False)
    phone_number = models.CharField(max_length=13, validators=[integer_validator])

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()


class Post(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

app/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views import generic
from django.views.generic import ListView, TemplateView

from app.form import ContactForm, LoginForm, RegisterForm
from app.models import Product, User
# from token import account_activation_token


def index(request):
    return render(request, 'app/index.html')



def about(request):
    return render(request,'app/about.html')


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            email_subject = f'New contact {form.cleaned_data["email"]}: {form.cleaned_data["subject"]}'
            email_message = form.cleaned_data['message']
            send_mail(email_subject, email_message, settings.CONTACT_EMAIL, settings.ADMIN_EMAIL)
            return render(request, 'app/succes.html')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'app/contact.html', context)


def single_post(request, product_id):
    product = Product.objects.filter(id=product_id).first()
    context = {
        'product': product
    }
    return render(request, 'app/single-post.html', context)

def blog(request):
    products = Product.objects.order_by('-id')
    context = {
        'products':products
    }
    return render(request, 'app/blog.html', context)






def login_view(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            if user:
                login(request, user)
                return redirect('index')

    return render(request, 'app/login.html', {'form':form})


def logout_view(request):
    logout(request)
    return render(request, 'app/logout.html')


class blogPage(ListView):
    template_name = 'app/blog.html'
    model = Product
    queryset = Product.objects.all()
    context_object_name = 'products'

#
# def register_view(request):
#     form = RegisterForm()
#     if request.method == "POST":
#         form = RegisterForm(request.POST)
#         if form.is_valid():
#             form.save()
#             send_email(form.data.get('email'), request, 'register')
#             messages.add_message(
#                 request,
#                 level=messages.INFO,
#                 message='Xabar yuborildi, emailingizni tekshiring'
#             )
#             return redirect('register')
#     return render(request, 'app/register.html', {'form': form})
#
def register_view(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('index')
    return render(request, 'app/register.html', {'form':form})





class BlogSearchView(ListView):
    template_name = 'app/blog.html'
    model = Product
    queryset = Product.objects.all()
    context_object_name = 'products'

    def get_queryset(self):
        title = self.request.GET.get('title')
        if title:
            return Product.objects.filter(title__icontains=title)


class Register(generic.CreateView):
    from_class = UserCreationForm
    success_url = reverse_lazy('index')
    template_name = 'app/register.html'

templates/app/about.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Firmbee.com - Free Project Management Platform for remote teams">
    <title>Clear blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <script src="https://kit.fontawesome.com/0e035b9984.js" crossorigin="anonymous"></script>
</head>
<body data-bs-spy="scroll" data-bs-target="#navbar-example" data-bs-offset="82">
      <header id="home">
        <nav id="#navbar" class="navbar dark dark navbar-expand-lg position-fixed top-0 w-100 py-2">
          <div class="container">
            <a class="navbar-brand" href="index.html"><img src="{% static 'img/logo-blog.png' %}" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav ms-auto">
                <a class="nav-link" href="{% url 'index' %}">home</a>
                <a class="nav-link active" href="{% url 'about' %}">about</a>
                <a class="nav-link" href="{% url 'contact' %}">contact</a>
                <a class="nav-link" href="{% url 'blog' %}">Blog</a>
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <div class="container">
          <div class="row mainmargin">
            <div class="col-md-8">
              <div class="about-page">
                <h2 class="underscore">Hi there, let's introduce you to the team...</h2>
                <p class="sup-header">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum sunt optio consequuntur ducimus odit. Deleniti optio saepe unde omnis. Sapiente aliquam repellendus error id veniam totam dolores recusandae non dolorum?</p>
                <div class="line"></div>
                <img  src="{% static 'img/meeting-2284501_1920.jpg' %}"  class="d-block w-100 mb-5"  alt="..." />
                <h4>Lorem ipsum dolor sit amet.</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo nemo enim culpa odit at in quia facere, hic est assumenda vel praesentium ipsam harum cupiditate necessitatibus iure quis provident sequi. Nemo nobis officiis magnam tenetur. Modi incidunt libero quod iste veritatis dolor id provident numquam ex, eum voluptas, quidem voluptates. Tempora in quae voluptas voluptatibus vero ad qui quisquam dolore obcaecati enim tenetur corporis temporibus facilis voluptate, incidunt iure eius. Laborum optio officiis consectetur sequi enim laboriosam quae quisquam facere, amet expedita.
                </p>
                <h5>Lorem ipsum dolor sit amet consectetur:</h5>
                <ul class="list-in-text">
                  <li>Lorem ipsum dolor sit amet consectetur.</li>
                  <li>Lorem ipsum dolor sit amet consectetur.</li>
                  <li>Lorem ipsum dolor sit amet consectetur.</li>
                </ul>
                <p>Distinctio nesciunt blanditiis beatae, exercitationem dicta aliquid aliquam soluta sapiente, vero dignissimos quam repellat expedita voluptas magnam repellendus pariatur consequatur deleniti sequi quaerat! Maiores harum nostrum numquam modi, animi quia eum nemo in eaque asperiores incidunt accusamus commodi a at placeat maxime deserunt eligendi quos qui officiis sequi! Necessitatibus voluptate sed, dignissimos esse aliquid repellendus. Quo accusamus sit incidunt magnam quis architecto nobis, eaque maxime, laboriosam molestiae placeat iure sequi mollitia quas consectetur non? Velit, iure ducimus. Illum, et qui temporibus nostrum deserunt voluptas quisquam quidem hic. Exercitationem impedit eveniet quis. Dignissimos temporibus sit pariatur dolor porro sed nesciunt. Tenetur harum necessitatibus explicabo, porro corporis in ex nobis dicta, quo sed consectetur molestiae rem aspernatur, neque perspiciatis accusantium?</p>
                <div class="features dark text-uppercase d-flex justify-content-around py-5 my-5">
                  <div class="feature-item text-center">
                    <p class="display-2">300</p>
                    <p>Satisfied Clients</p>
                  </div>
                  <div class="feature-item text-center">
                    <p class="display-2">20</p>
                    <p>Awoards</p>
                  </div>
                  <div class="feature-item text-center">
                    <p class="display-2">400</p>
                    <p>Completed Projects</p>
                  </div>
                </div>
                <p>Distinctio nesciunt blanditiis beatae, exercitationem dicta aliquid aliquam soluta sapiente, vero dignissimos quam repellat expedita voluptas magnam repellendus pariatur consequatur deleniti sequi quaerat! Maiores harum nostrum numquam modi, animi quia eum nemo in eaque asperiores incidunt accusamus commodi a at placeat maxime deserunt eligendi quos qui officiis sequi! Necessitatibus voluptate sed, dignissimos esse aliquid repellendus. Quo accusamus sit incidunt magnam quis architecto nobis, eaque maxime, laboriosam molestiae placeat iure sequi mollitia quas consectetur non? Velit, iure ducimus. Illum, et qui temporibus nostrum deserunt voluptas quisquam quidem hic. Exercitationem impedit eveniet quis. Dignissimos temporibus sit pariatur dolor porro sed nesciunt. Tenetur harum necessitatibus explicabo, porro corporis in ex nobis dicta, quo sed consectetur molestiae rem aspernatur, neque perspiciatis accusantium?</p>
              </div>
            </div>
            <div class="sidebar col-md-4">
              <div class="input-group">
                <div class="form-outline">
                  <input id="search-input" type="search" id="form1" class="form-control" placeholder="search" />
                </div>
                <button id="search-button" type="button" class="btn dark">
                  <i class="fas fa-search"></i>
                </button>
              </div>
              <div class="recent-posts pt-5">
                <h4 class="mb-3">RECENT POSTS</h4>
                <div class="post-item">
                  <a href="single-post.html" class="post-title">Lorem ipsum dolor sit amet consectetur adipisicing elit.</a>
                  <div class="post-meta">
                    <span><i class="far fa-user"></i> Posted by someone</span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 0 comments</span>
                  </div>
                  <p class="post-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt perspiciatis ex ipsam similique blanditiis. Culpa hic quia...</p>
                </div>
                <div class="post-item">
                  <a href="single-post.html" class="post-title">Lorem ipsum dolor sit amet consectetur adipisicing elit.</a>
                  <div class="post-meta">
                    <span><i class="far fa-user"></i> Posted by someone</span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 0 comments</span>
                  </div>
                  <p class="post-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt perspiciatis ex ipsam similique blanditiis. Culpa hic quia...</p>
                </div>
                <div class="post-item">
                  <a href="single-post.html" class="post-title">Lorem ipsum dolor sit amet consectetur adipisicing elit.</a>
                  <div class="post-meta">
                    <span><i class="far fa-user"></i> Posted by someone</span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 0 comments</span>
                  </div>
                  <p class="post-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt perspiciatis ex ipsam similique blanditiis. Culpa hic quia...</p>
                </div>
                <a class="main-button">View all posts</a>
                <div class="popular pt-5">
                  <h4 class="mb-3">READ MOST POPULAR ARTICLES</h4>
                  <div class="card bg-dark text-white">
                    <img src="{% static 'img/architecture-1857175_1920.jpg' %}" class="card-img" alt="...">
                    <div class="card-img-overlay p-3">
                      <div class="text-overlay">
                      <h5 class="card-title text-uppercase">Lorem, ipsum dolor sit amet consectetur </h5>
                      <div class="line"></div>
                      <div class="card-text article-meta">
                        <span><i class="far fa-user"></i> Posted by someone </span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 300 comments</span>
                      </div>
                      <button class="card-button">Read article</button>
                      </div>
                    </div>
                  </div>
                  <div class="card bg-dark text-white">
                    <img src="{% static 'img/castle-1998435_1920.jpg' %}" class="card-img" alt="...">
                    <div class="card-img-overlay p-3">
                      <div class="text-overlay">
                      <h5 class="card-title text-uppercase">Lorem, ipsum dolor sit amet consectetur </h5>
                      <div class="line"></div>
                      <div class="card-text article-meta">
                        <span><i class="far fa-user"></i> Posted by someone </span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 300 comments</span>
                      </div>
                      <button class="card-button">Read article</button>
                      </div>
                    </div>
                  </div>
                  <div class="card bg-dark text-white">
                    <img src="{% static 'img/staircase-274614_1920.jpg' %}" class="card-img" alt="...">
                    <div class="card-img-overlay p-3">
                      <div class="text-overlay">
                      <h5 class="card-title text-uppercase">Lorem, ipsum dolor sit amet consectetur </h5>
                      <div class="line"></div>
                      <div class="card-text article-meta">
                        <span><i class="far fa-user"></i> Posted by someone </span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 300 comments</span>
                      </div>
                      <button class="card-button">Read article</button>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
            </div>
          </div>
        </div>
      </main>
      <footer class="text-center text-uppercase py-5">
        <div class="footer-icons ">
          <a href=""><img src="{% static 'img/facebook-footer.svg' %}" alt=""></a>
          <a href=""><img src="{% static 'img/instagramm-footer.svg' %}" alt=""></a>
          <a href=""><img src="{% static 'img/pinterest-footer.svg' %}" alt=""></a>
        </div>
        <div class="copyright pt-4 text-muted text-center">
          <p>&copy; 2022 YOUR-DOMAIN | Created by <a href="https://firmbee.com/solutions/free-invoicing-app-billing-software/" title="Firmbee - Free Invoicing App" target="_blank">Firmbee.com</a> </p>
          <!--
          This template is licenced under Attribution 3.0 (CC BY 3.0 PL),
          You are free to: Share and Adapt. You must give appropriate credit, you may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
          -->
      </div>
      </footer>
      <div class="fb2022-copy">Fbee 2022 copyright</div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/app/activate.html
{% autoescape off %}
    Hi {{ User.username }},

    Please click on the link below to confirm your registration:

    http://{{ domain }}/activate/{{ uid }}/{{ token }}
{% endautoescape %}

templates/app/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Firmbee.com - Free Project Management Platform for remote teams"> 
    <title>Clear blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
    <script src="https://kit.fontawesome.com/0e035b9984.js" crossorigin="anonymous"></script>
</head>
<body data-bs-spy="scroll" data-bs-target="#navbar-example" data-bs-offset="82">
      <header id="home">
        <nav id="#navbar" class="navbar dark dark navbar-expand-lg position-fixed top-0 w-100 py-2">
          <div class="container">
            <a class="navbar-brand" href=""><img src="{% static 'img/logo-blog.png' %}" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav ms-auto">
                <a class="nav-link" href="{% url 'index' %}">home</a>
                <a class="nav-link" href="{% url 'about' %}">about</a>
                <a class="nav-link active" href="{% url 'contact' %}">contact</a>
                <a class="nav-link" href="{% url 'blog' %}">Blog</a>
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main>
        <div class="container">
          <div class="row mainmargin">
            <div class="col-md-8">
              <div class="contact-page">
                <h2 class="underscore mb-5">Please let us know if you have any questions</h2>
                <div class="line"></div>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum sunt optio consequuntur ducimus odit. Deleniti optio saepe unde omnis. Sapiente aliquam repellendus error id veniam totam dolores recusandae non dolorum?</p>
                <div class="line"></div>
                <form action="" method="post">
                    {% csrf_token %}
                    <tr>
                        <th>
                             <label for="id_email">Email:</label>
                        </th>
                        <td>
                            <input type="email" name="email" maxlength="254" required id="id_email">
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_subject">Subject:</label>
                        </th>
                        <td>
                            <input type="text" name="subject" maxlength="255" required id="id_subject">
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <label for="id_message">Message:</label>
                        </th>
                        <td>
                            <textarea name="message" cols="40" rows="10" required id="id_message"></textarea>
                        </td>
                    </tr>
                    <input type="submit" value="Submit">
                </form>
              </div>
            </div>
            <div class="sidebar col-md-4">
              <div class="input-group">
                <div class="form-outline">
                  <input id="search-input" type="search" id="form1" class="form-control" placeholder="search" />
                </div>
                <button id="search-button" type="button" class="btn dark">
                  <i class="fas fa-search"></i>
                </button>
              </div>
              <div class="recent-posts pt-5">
                <h4 class="mb-3">RECENT POSTS</h4>
                <div class="post-item">
                  <a href="single-post.html" class="post-title">Lorem ipsum dolor sit amet consectetur adipisicing elit.</a>
                  <div class="post-meta">
                    <span><i class="far fa-user"></i> Posted by someone</span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 0 comments</span>
                  </div>
                  <p class="post-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt perspiciatis ex ipsam similique blanditiis. Culpa hic quia...</p>
                </div>
                <div class="post-item">          
                  <a href="single-post.html" class="post-title">Lorem ipsum dolor sit amet consectetur adipisicing elit.</a>
                  <div class="post-meta">
                    <span><i class="far fa-user"></i> Posted by someone</span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 0 comments</span>
                  </div>
                  <p class="post-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt perspiciatis ex ipsam similique blanditiis. Culpa hic quia...</p>
                </div>
                <div class="post-item">           
                  <a href="single-post.html" class="post-title">Lorem ipsum dolor sit amet consectetur adipisicing elit.</a>
                  <div class="post-meta">
                    <span><i class="far fa-user"></i> Posted by someone</span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 0 comments</span>
                  </div>
                  <p class="post-content">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt perspiciatis ex ipsam similique blanditiis. Culpa hic quia...</p>
                </div>
                <a class="main-button">View all posts</a>
                <div class="popular pt-5">
                  <h4 class="mb-3">READ MOST POPULAR ARTICLES</h4>
                  <div class="card bg-dark text-white">
                    <img src="{% static 'img/architecture-1857175_1920.jpg' %}" class="card-img" alt="...">
                    <div class="card-img-overlay p-3">
                      <div class="text-overlay">
                      <h5 class="card-title text-uppercase">Lorem, ipsum dolor sit amet consectetur </h5>
                      <div class="line"></div>
                      <div class="card-text article-meta">
                        <span><i class="far fa-user"></i> Posted by someone </span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 300 comments</span>
                      </div>
                      <button class="card-button">Read article</button>
                      </div>
                    </div>
                  </div>
                  <div class="card bg-dark text-white">
                    <img src="{% static 'img/castle-1998435_1920.jpg' %}" class="card-img" alt="...">
                    <div class="card-img-overlay p-3">
                      <div class="text-overlay">
                      <h5 class="card-title text-uppercase">Lorem, ipsum dolor sit amet consectetur </h5>
                      <div class="line"></div>
                      <div class="card-text article-meta">
                        <span><i class="far fa-user"></i> Posted by someone </span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 300 comments</span>
                      </div>
                      <button class="card-button">Read article</button>
                      </div>
                    </div>
                  </div>
                  <div class="card bg-dark text-white">
                    <img src="{% static 'img/staircase-274614_1920.jpg' %}" class="card-img" alt="...">
                    <div class="card-img-overlay p-3">
                      <div class="text-overlay">
                      <h5 class="card-title text-uppercase">Lorem, ipsum dolor sit amet consectetur </h5>
                      <div class="line"></div>
                      <div class="card-text article-meta">
                        <span><i class="far fa-user"></i> Posted by someone </span><span><i class="far fa-calendar"></i> 30 07 2021</span><span><i class="far fa-comment-alt"></i> 300 comments</span>
                      </div>
                      <button class="card-button">Read article</button>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
            </div>
          </div>
        </div> 
      </main>
      <footer class="text-center text-uppercase py-5">  
        <div class="footer-icons ">
          <a href=""><img src="{% static 'img/facebook-footer.svg' %}" alt=""></a>
          <a href=""><img src="{% static 'img/instagramm-footer.svg' %}" alt=""></a>
          <a href=""><img src="{% static 'img/pinterest-footer.svg' %}" alt=""></a>
        </div>
        <div class="copyright pt-4 text-muted text-center">
          <p>&copy; 2022 YOUR-DOMAIN | Created by <a href="https://firmbee.com/solutions/free-invoicing-app-billing-software/" title="Firmbee - Free Invoicing App" target="_blank">Firmbee.com</a> </p>
          <!--
          This template is licenced under Attribution 3.0 (CC BY 3.0 PL),
          You are free to: Share and Adapt. You must give appropriate credit, you may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
          --> 
      </div>
      </footer>
      <div class="fb2022-copy">Fbee 2022 copyright</div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
      <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/app/succes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Thank you for your inquiry</h1>
<p>Your contact information and message was successfully submitted.</p>

</body>
</html>